apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:  # these are replicaset labels
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:   # these are used to select the pod to create replicas
      app: mysql
      tier: db
      project: expense
  #this is pod defination    
  template:
    metadata:
      labels:  # these are pod labels
         app: mysql
         tier: db
         project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:{{ .Values.deployment.imageVersion }}
        

---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
     app: mysql
     tier: db
     project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port
